# Generated by Django 5.0.4 on 2024-04-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Account_Number', models.CharField(max_length=20)),
                ('City', models.CharField(max_length=20)),
                ('Phone', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Address', models.CharField(max_length=50)),
                ('Process_Name', models.CharField(max_length=20)),
                ('DOB', models.DateField(max_length=20)),
            ],
        ),
    ]
