# Generated by Django 5.0.4 on 2024-04-17 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='SteftoNo',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Account_Number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Phone',
            field=models.IntegerField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('EmpCode', models.CharField(max_length=10)),
                ('Process', models.CharField(blank=True, max_length=20)),
                ('RegisterDate', models.DateTimeField(auto_now_add=True)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'custom_user_profile_table',
            },
        ),
    ]
